name: Continuos Integration
#evento que chama workflow
on: push
jobs:
   continuos-integration:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v3
         - name: Using Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 18
         - name: Install dependencies
           run: |
                npm cache clean --force
                npm install
                npm run build